name: Deployment
on:
  push:
    branches:
      - master
jobs:
  sync:
    name: Verify and sync data to IPFS
    runs-on: ubuntu-latest

    env:
      PINATA_KEY: ${{ secrets.PINATA_KEY }}
      PINATA_SECRET: ${{ secrets.PINATA_SECRET }}
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_SECRET: ${{ secrets.CLOUDFLARE_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Verify data
        run: node scripts/verify.mjs

      - name: Generate build artifact
        run: node scripts/build.mjs

      - name: Sync to IPFS
        id: upload
        uses: nymmrx/ipfs-deploy@master
        with:
          path: "./build"
          pin-name: Yearn Meta
          pinata-key: ${{ secrets.PINATA_KEY }}
          pinata-secret: ${{ secrets.PINATA_SECRET }}
          cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE }}
          cloudflare-secret: ${{ secrets.CLOUDFLARE_SECRET }}
          record-domain: yearn.network
          record-name: _dnslink.meta
